# Generated by Django 4.1.7 on 2023-03-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RsmMeterMaster',
            fields=[
                ('meter_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('meter_serial_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstantModel',
            fields=[
                ('auto_index', models.AutoField(primary_key=True, serialize=False)),
                ('_00_00_01_00_00_FF', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_timestamp', models.DateTimeField()),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instant', to='dataapp.rsmmetermaster')),
            ],
        ),
    ]
