# Generated by Django 4.1.7 on 2023-03-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmodel',
            name='_00_00_01_00_00_FF',
        ),
    ]
